### ISSUE TITLE
Wii rockband drum, "could not find/open device"

### ISSUE THREAD

**Issue by ssj71** [rbdrum2midi/rbdrum2midi#2]
From user Zac Townsend:

I just picked up a Wii Rockband drum controller the other day... it's USB, and I believe it's the original one with only one jack (for bass drum). No cymbals.

Anyways, I have been trying hard to get this thing to work as a midi controller. I got your program to compile, version 0.5, first using cmake and then using the other method I read in this forum (gcc main.c rbkit.c rb1kit.c ghkit.c alsadriver.c jackdriver.c -o rbdrum2midi -lasound -lusb-1.0 -ljack). Tried running it as root, got the same results. Tried adding the udev file... didn't help.

I have a feeling it has something to do with the distro I'm running. Just a few days ago I switched to AV Linux, which is based on Debian (although a version from years ago, the "squeeze" release). Apparently this is the kind of distro you're not really supposed to upgrade, or else it causes problems. So I have a feeling it has something to do with packages being older on my system than they need to be. I took a gamble and updaged libasound2 and libusb, but unfortunately that did not help either.

Any ideas? Thanks...

**Comment by ssj71** [comment]
Hi Zac:

We may have added support for this since moving to github. Try downloading from here and test, and if that doesn't work then we've just never had a user with the same device as you have. Please run in a terminal the command "lsusb" and post the output here. We'll add support for it.

Thanks!

**Comment by randomas** [comment]
I checked the code because I remembered we had added support for a Wii drumkit, and in fact it's in there, but probably it's for a rb3 or 2 kit and it sounds like yours is an RB 1 kit. 
the lsusb command will tell us if it's a different kit or if we have to hunt for a different issue.

**Comment by ssj71** [comment]
I think this is now resolved with the latest changes to support wii rb1 kits.
