### ISSUE TITLE
Harmonix Guitar Hero Drum Kit (X-Box) **DebugOutputProvided**

### ISSUE THREAD

**Issue by gavox-z** [rbdrum2midi/rbdrum2midi#3]
Thanks _so much_ for your hard work - this is turning into a really great Hacker'Z'app.   Seriously, thank you again.  The output etc below was generated using the Harmonix Guitar Hero Drum Kit (Model # 822149) for X-Box .  

It's a pleasure to be a part of this project (in the most miniscule possible way, but still).  Please e-mail me at "gbrwcky@uvic.ca" to let me know when support has been added for this kit!
## Bus 001 Device 008: ID 1bad:0003

gavin@Inception[gavin] lsusb                                          [11:50PM]
Bus 002 Device 002: ID 058f:a001 Alcor Micro Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 008: ID 1bad:0003 Harmonix Music Drum Kit for Xbox 360
Bus 001 Device 010: ID 0763:1015 Midiman M-Audio Keystation
Bus 001 Device 007: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 006: ID 045e:0745 Microsoft Corp. Nano Transceiver v1.0 for Bluetooth
Bus 001 Device 005: ID 413c:2107 Dell Computer Corp. 
Bus 001 Device 002: ID 0409:0058 NEC Corp. HighSpeed Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 0d8c:0105 C-Media Electronics, Inc. CM108 Audio Controller
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
## You rock!!

gavin@Inception[src] sudo rbdrum2midi -dbg                            [12:17AM]
claimed interface
Setting up alsa
client:port = 130:0
Returning 1
Debug Mode Enabled..
00140001 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Bass Drum Pedal
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Release (?)
00140020 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Low Tom
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140020 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Low Tom
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140080 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Hi-Hat (closed)
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140080 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Hi-Hat (closed)
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140040 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Hi Tom
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140040 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Hi Tom
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140010 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Snare
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140010 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Snare
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140800 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Play Forward
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140200 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Volume Down
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140400 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Play Backwards (Reverse)
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140100 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Volume Up
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140040 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Deeper Bass Drum
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140010 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Open Hi-Hat
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140020 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Fuller Snare Drum
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140080 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Big Crash Cymbal
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00142000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## BPM SLOWER
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140004 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 ## Funk Sound Effect
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00141000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 # BPM FASTER
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
## The output below is identical but without comments

gavin@Inception[src] sudo rbdrum2midi -dbg                            [12:17AM]
claimed interface
Setting up alsa
client:port = 130:0
Returning 1
Debug Mode Enabled..
00140001 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2 
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140020 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140020 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140080 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140080 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140040 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140040 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140010 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140010 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140800 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140200 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140400 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140100 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140040 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140010 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140020 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140080 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00142000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140004 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00141000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2
00140000 00000000 00000000 00000000 00000000 4495f8fe 7f0000 kit type=2

**Comment by randomas** [comment]
Thank you for the kind words gavox!
It looks like your kit should already work/be supported. It looks like an original rb1 kit (which unfortunately does not do velocity AFAIK). 
Could you please detail the steps you use to try and get it working with jack and hydrogen, and which version you're using. 
Also thanks for sending the debug code, could you please indicate what button/pad (eg, red, yellow, kick etc) you were pressing, rather than what you would like to map it to. When it's working you can remap the pads to different midi channels from the command line so that should be a non issue. 
Unfortunately I have little time to look at the code so if that needs to be tweaked ssj71 is your man, but I can help with the general setup.

Thanks for contributing to the project.

Matt

**Comment by gavox-z** [comment]
Hi - should have that for you in the next day or sø!

Gavin

**Comment by ssj71** [comment]
@gavox-z sorry its been forever but I'm taking a minute to try to update this project. Unfortunately your kit sends identical information for the cymbals as the pads, so there's no way to send different notes for the two. Are you still interested in using this project?

**Comment by ssj71** [comment]
Please re-open if this issue still applies to you
